smarty:
  templates_dir: /templates/
  templates_c_dir: /templates/compiled/
  cache_dir: /cache/
  config_dir: /config/
doctrine:
  connection:
    driver: pdo_mysql
    host: localhost
    dbname: onlineshop
    user: shop
    password: Testshop123.
  devMode: true
  entities_dir: /classes/Models
  proxy_dir: /cache/proxy
productsImgDir: /assets/img/products/
sectionsImageDir: /assets/img/sections/
allowedFiles:
  jpg: image/jpeg
  png: image/png
  gif: image/gif
itemsOnPage: 12