#Файл с секретными данными(ключи, пароли, явки...). Имя оригинального файла: secret.yml

#mail:
#  sendgridKey: ApiKey for Sendgrid
#  adminMail: admin mail
#  sender: sender mail
#admin_credentials:
#  login: admin login
#  password: admin password